use_frameworks!

platform :ios, '10.0'

target 'ZCMenuControl_Example' do
  pod 'ZCMenuControl', :path => '../'

  target 'ZCMenuControl_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
