use_frameworks!

platform :ios, '10.0'

target 'ZCMenuControl_Example' do
  pod 'ZCMenuControl', :git =>"https://github.com/cbhy1988love/ZCMenuControl.git"

  target 'ZCMenuControl_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
