use_frameworks!

platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'ZCMenuControl_Example' do
  pod 'ZCMenuControl'
  target 'ZCMenuControl_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
